### PR TITLE
fix missing symbols when building with cmake

### PR DESCRIPTION
**Pull request by FernetMenta**

### CODE REVIEW

**Comment by FernetMenta** [comment]
@wsnipex @fetzerch is this correct?
currently Kodi crashes due to missing symbols http://trac.kodi.tv/ticket/16932

**Comment by wsnipex** [comment]
I'd try with $abs_top_builddir which is the absolute path.

**Comment by Jalle19** [comment]
Wrong button?

**Comment by FernetMenta** [comment]
nope, this change is obsolete

**Pull request closed without merging**
